openapi: 3.0.0
info:
  title: Dictionary API
  description: A RESTful API for dictionary management with user authentication and word lookup
  version: 1.0.0
servers:
  - url: /api
    description: API base URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
    Word:
      type: object
      properties:
        word:
          type: string
        language:
          type: string
    History:
      type: object
      properties:
        word:
          type: string
        added:
          type: string
          format: date-time
    Favorite:
      type: object
      properties:
        word:
          type: string
        added:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        message:
          type: string
    Token:
      type: object
      properties:
        token:
          type: string
    PaginatedResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: string
        totalDocs:
          type: integer
        page:
          type: integer
        totalPages:
          type: integer
        hasNext:
          type: boolean
        hasPrev:
          type: boolean
paths:
  /:
    get:
      summary: Get API status
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/signin:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /entries/en:
    get:
      summary: Get list of words
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: List of words
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
                  totalDocs:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  hasNext:
                    type: boolean
                  hasPrev:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /entries/en/{word}:
    get:
      summary: Get word definition
      security:
        - bearerAuth: []
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Word definition
          headers:
            x-cache:
              schema:
                type: string
                enum: [HIT, MISS]
            x-response-time:
              schema:
                type: integer
        '404':
          description: Word not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /entries/en/{word}/favorite:
    post:
      summary: Add word to favorites
      security:
        - bearerAuth: []
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Word added to favorites
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /entries/en/{word}/unfavorite:
    delete:
      summary: Remove word from favorites
      security:
        - bearerAuth: []
      parameters:
        - name: word
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Word removed from favorites
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/me:
    get:
      summary: Get user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/me/history:
    get:
      summary: Get user search history
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: User history
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/History'
                  totalDocs:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  hasNext:
                    type: boolean
                  hasPrev:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/me/favorites:
    get:
      summary: Get user favorites
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: User favorites
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Favorite'
                  totalDocs:
                    type: integer
                  page:
                    type: integer
                  totalPages:
                    type: integer
                  hasNext:
                    type: boolean
                  hasPrev:
                    type: boolean
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
